spring:
  devtools:
    restart:
      enabled: true
  data:
    mongodb:
      host: localhost
      port: 27017
      username: mrlanu
      password: mrlanu
      database: travian

authorization:
  token:
    header:
      name: Authorization
      prefix: Bearer
    secret: hfgry463hf746hf573ydh475fhy5739
    expiration_time: 86400000
