package io.lanu.travian.game.models.buildings;

public enum BuildingsID {
    WOODCUTTER, CLAY_PIT, IRON_MINE, CROPLAND, RALLY_POINT, MAIN, GRANARY, WAREHOUSE, BARRACK, MARKETPLACE, ACADEMY,
    BLACKSMITH, EMPTY
    /*WOODCUTTER, CLAY_PIT, IRON_MINE, CROPLAND, SAWMILL, BRICKYARD, IRON_FOUNDRY, GRAIN_MILL, BAKERY, WAREHOUSE, GRANARY,
    ARMORY, BLACKSMITH, ARENA, MAIN, RALLY_POINT, MARKETPLACE, EMBASSY, BARRACK, STABLES, WORKSHOP,
    ACADEMY, CRANNY, TOWN_HALL, RESIDENCE, PALACE, TRADE_OFFICE, GREAT_BARRACKS, GREAT_STABLES, CITY_WALL, EARTH_WALL,
    PALISADE, EMPTY*/
}
